name: Extension Build Prod

on:
  push:
    branches: main

jobs:
  build_extension:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: scrapping coin list
        run: |-
          python infra/scrapper/coin_list_gen.py  
      - name: scrapping price list
        run: |-
          python infra/scrapper/coin_price_gen.py
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: |-
          cd packages/browserExtension && yarn && yarn build-prod
          
      - uses: actions/upload-artifact@v3
        with:
          name: prod-extension
          path: packages/browserExtension/build-prod
