name: Build and Push to GCR

on:
  push:
    branches: sandbox/*


env:
  GITHUB_SHA: ${{ github.sha }} 
  GITHUB_REF: ${{ github.ref }} 
  IMAGE: insight-platform
  REGISTRY_HOSTNAME: gcr.io
  GAR_LOCATION: us-central1
  GKE_CLUSTER: sdl-cluster-dev-zvfsd
  GKE_ZONE: us-central1-a
  PROJECT_ID: snickerdoodle-insight-stackdev


jobs:
  setup-build-publish-deploy:
    name: Setup, Build, and Publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        

    - name: Docker configuration
      run: |-
        gcloud --quiet auth configure-docker $GAR_LOCATION-docker.pkg.dev
        
    - name: Build protocol
      run: |-
        JIRA_TICKET=$(echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})" | grep -Eo '[A-Za-z0-9]*-[0-9]*' | awk '{print tolower($0)}')
      
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol:$GITHUB_SHA" \
          --build-arg DOMAIN="extension.$JIRA_TICKET.snickerdoodle.dev" \
          --build-arg RPC_PROVIDER="https://$JIRA_TICKET.snickerdoodle.dev/" \
          --build-arg CONTROL_CHAIN_ID=31337 \
          --build-arg BUILD_ENV=development \
          --build-arg INFURA_ID=72827ccd538446f2a20e35a632664c52 \
          --build-arg GAPI_CLIENT_ID=332580693256-mifj8rkovvlc332n8gtllpdl93e6nvio.apps.googleusercontent.com \
          -f ./packages/extension-onboarding/Dockerfile \
          .
  
    # Push the Docker image to Google Artifact Registry
    - name: Publish protocol
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/insight-platform/protocol:$GITHUB_SHA"

    - name: Deploy to GCR
      run: |-
        JIRA_TICKET=$(echo $GITHUB_REF | grep -Eo '[A-Z0-9]*-[0-9]*' | awk '{print tolower($0)}')
        GKE_CLUSTER=$(gcloud container clusters list --format="csv(name)" | grep $JIRA_TICKET)
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
        
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
        cd infra/
        helm install  insight-platform-protocol ./insight-platform-protocol || true
        helm upgrade --reuse-values --set InsightPlatformProtocol.Image.Tag=$GITHUB_SHA  insight-platform-protocol ./insight-platform-protocol 
